config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "groups#index"
  resources :users, only:  [:index,:edit, :update]
  resources :groups, only: [:index, :new, :create, :edit, :update] do
    resources :messages, only: [:index, :create]

  namespace :api do
    resources :messages,only: :index,defaults:{format:'json'}
  end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :messages
  has_many :user_groups
  has_many :users, through: :user_groups
  validates :name, presence: true, uniqueness: true

  def show_last_message
    if (last_message = messages.last).present?
      last_message.body? ? last_message.body : '画像が投稿されています'
    else
      'まだメッセージはありません。'
    end
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :group
  validates :body, presence:true,unless: :image?
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

        has_many :messages
        has_many :groups, through: :user_groups
        has_many :user_groups
end

app/models/user_group.rb
class UserGroup < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/controllers/api/messages_controller.rb
class Api::MessagesController < ApplicationController
  def index
    group=Group.find(params[:group_id])
    last_message_id = params[:id].to_i
    @messages=group.messages.includes(:user).where("id>#{last_message_id}")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,keys:[:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only:[:edit,:update]
  def index
    @users=User.where()
  end

  def new
    @group=Group.new
    @group.users << current_user
  end

  def create
    @group=Group.new(group_params)
    if @group.save
      redirect_to root_path, notice:'グループを作成しました'
    else
      render :new
    end
  end

  def edit
  end

  def update
    
    if @group.update(group_params)  
    redirect_to group_messages_path(@group),
    notice:"グループを更新しました"
    else
      render :edit
    end
  end 

  private
  def group_params
    params.require(:group).permit(:name, user_ids: [] )
  end

  def set_group
    @group=Group.find(params[:id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_group
  def index
    @message=Message.new
    @messages=@group.messages.includes(:user)
    @user=@group.users.includes(:messages)
  end

  def create
    @message=@group.messages.new(message_params)
    if @message.save
      respond_to do |format|
        format.html{redirect_to group_messages_path,notice:"メッセージが送信されました"}
        format.json
      end
    else 
      @messages=@group.messages.includes(:user)
      flash.now[:alart]="メッセージを入力してください"
      render :index
    end 
    
  end

  private
  def message_params
    params.require(:message).permit(:body, :image).merge(user_id: current_user.id)
  end

  def set_group
    @group=Group.find(params[:group_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    return nil if params[:keyword]==""
    @users=User.where(['name LIKE ?',"%#{params[:keyword]}%"]).where.not(id:current_user.id).limit(5)
    respond_to do |format|
      format.html
      format.json
    end
  end

  def edit
  end

  def update
   if current_user.update(user_params)
    redirect_to root_path
   else
    render :edit
   end
  end
  private
  def user_params
    params.require(:user).permit(:name, :email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_form.html.haml
= form_for group do |f|
  - if group.errors.any?
    .chat-group-form__errors
      %h2= "#{group.errors.full_messages.count}件のエラーが発生しました。"
      %ul
        - group.errors.full_messages.each do |message|
          %li= message
  .chat-group-form__field
    .chat-group-form__field--left
      = f.label :name, "グループ名", class: 'chat-group-form__label'
    .chat-group-form__field--right
      = f.text_field :name, class: 'chat__group_name chat-group-form__input', placeholder: 'グループ名を入力してください'
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{:for => "chat_group_チャットメンバーを追加"} チャットメンバーを追加
    .chat-group-form__field--right
      .chat-group-form__search.clearfix
        %input#user-search-field.chat-group-form__input{:placeholder => "追加したいユーザー名を入力してください", :type => "text"}/
      #user-search-result

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{:for => "chat_group_チャットメンバー"} チャットメンバー
    .chat-group-form__field--right
      #chat-group-users.js-add-user
        .chat-group-user.clearfix.js-chat-member
          %input{name: "group[user_ids][]", type: "hidden", value: current_user.id}
          %p.chat-group-user__name= current_user.name

        - group.users.each do |user|
          - if current_user.name != user.name
            .chat-group-user.clearfix.js-chat-member
              %input{name: "group[user_ids][]", type: "hidden", value: user.id}
              %p.chat-group-user__name
                = user.name 
              %a.user-search-remove.chat-group-user__btn.chat-group-user__btn--remove.js-remove-btn
                削除
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit class: 'chat-group-form__action-btn'

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = render partial: 'form',locals: { group: @group}

app/views/groups/index.html.haml
= render "messages/side_bar"

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = render partial: 'form', locals: { group: @group }

app/views/messages/_main_chat.html.haml
.main-chat
 .main-chat__group-info
  .main-chat__group-info__title
   .main-chat__group-info__title--name
    #{@group.name}
   .main-chat__group-info__title--member
    メンバー:
    - @user.each do |user|
     #{user.name}
  .main-chat__group-info__edit
   =link_to  "/groups/#{@group.id}/edit",class:'edit' do
    .main-chat__group-info__edit__string
     Edit
 .main-chat__message-list

  .main-chat__message-list__box
   .main-chat__message-list__box__one
   - @messages.each do |messe|
    .main-chat__message-list__box__one__upper{data:{message:{id:messe.id}}}
     .main-chat__message-list__box__one__upper__name
      #{messe.user.name} 
     .main-chat__message-list__box__one__upper__datetime
      #{messe.created_at}
    .main-chat__message-list__box__one__downer__body
     #{messe.body} 
    .main-chat__message-list__box__one__downer__image
     = image_tag messe.image.url if messe.image.present?

 .main-chat__message-form
  .main-chat__message-form__form-area
   .main-chat__message-form__form-area__frame
    =form_for [@group, @message] do |f|
     =f.text_field :body, class: 'text-form',placeholder:'ここに入力'
     .main-chat__message-form__form-area__frame--file
      =f.label :image, class: 'input-box__image' do
       =f.file_field :image, class: 'none'
       =icon('fas', 'image')
      .main-chat__message-form__form-area__frame__file--none
     .main-chat__message-form__form-area__send
      =f.submit 'Send',class: 'send'

app/views/messages/_side_bar.html.haml
.side-bar
 .side-bar__user-name
  .side-bar__user-name--user-menu
   .side-bar__user-name--user-menu--name
    #{current_user.name}
   .side-bar__user-name--user-menu--icon
    =link_to new_group_path,class:"icon" do
     =icon('far','edit')
    =link_to edit_user_path(current_user),class:"icon" do
     =icon('fa','cog')
 .side-bar__group-list
  - current_user.groups.each do |group|
   .side-bar__group-list__group
    =link_to "/groups/#{group.id}/messages" do 
     .side-bar__group-list__group__name
      =group.name
     .side-bar__group-list__group__latest
      =group.show_last_message

  -# .side-bar__group-list__group
  -#  .side-bar__group-list__group__name
  -#   ここがグループ名2
  -#  .side-bar__group-list__group__latest
  -#   ここが最新メッセージ
  -# .side-bar__group-list__group
  -#  .side-bar__group-list__group__name
  -#   ここがグループ名3 
  -#  .side-bar__group-list__group__latest
  -#   ここが最新メッセージ

app/views/messages/index.html.haml
.wrapper
  = render "side_bar"
  = render "main_chat"

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト" ,destroy_user_session_path, method: :delete ,class:'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'